---
chdir: "/home/deploy/snowooo/current"
environment: production
timeout: 30
log: "/home/deploy/snowooo/shared/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 3
socket: "/tmp/thin.sock"
daemonize: true
